replicaCount: 1
image:
  registry: ghcr.io
  repository: monakhovm
  tag: v1.0.16-e53d3cc
  os: linux
  arch: amd64
secret:
  telegram:
    name: telegram
    tokenKey: telegram_token
    token: ''
    envName: TELE_TOKEN
  imgbun:
    name: imgbun
    tokenKey: imgbun_token
    token: ''
    envName: IMGBUN_API_KEY
service:
  port: 80
  type: ClusterIP
autoscaling:
  enabled: false
  minReplicas: 1
ingress:
  enabled: false
serviceAccount:
  create: true
  annotations: {}
  name: ""
env:
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.monitoring.svc.cluster.local:4317"
serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus
  path: /metrics
  interval: 15s
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
