name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
    
        - name: Run tests
          run: make test
    
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GH_TOKEN }}
    
        - name: Build and push Docker image
          env:
            APP: "kbot"
            REGISTRY: ghcr.io/${{ github.actor }}
          run: make image push

    cd:
        name: CD
        runs-on: ubuntu-latest

        needs: ci
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - run: |
            IMAGE_TAG=$(git describe --tags --abbrev=0)
            VERSION="${IMAGE_TAG}-$(git rev-parse --short HEAD)"

            echo "Generated IMAGE_TAG: ${IMAGE_TAG}"
            echo "Generated VERSION: ${VERSION}"

            echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
            echo "VERSION=${VERSION}" >> $GITHUB_ENV

        - uses: mikefarah/yq@master
          with:
            cmd: |
              yq -i '.version = strenv(IMAGE_TAG)' helm/Chart.yaml
              yq -i '.appVersion = strenv(IMAGE_TAG)' helm/Chart.yaml
              cat helm/Chart.yaml

              yq -i '.image.tag = strenv(VERSION)' helm/values.yaml
              cat helm/values.yaml
              
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GH_TOKEN }}
    
        - name: Package and Push Helm chart
          env:
            APP: "kbot"
            REGISTRY: ghcr.io/${{ github.actor }}
          run: make helmchart
